### ISSUE TITLE
Can not stop scheduled jobs from running

### ISSUE THREAD

**Issue by rocketedaway** [sidekiq-cron/sidekiq-cron#421]
I have a `schedule.yml` file which looks similar to the following:

```yml
foo:
  cron: "0 0 * * *" # Everyday at midnight
  class: "FooJob"

bar:
  cron: "0 20 * * *" # Everyday at 8pm
  class: "BarJob"
```

I wanted to stop a job from running so I took a look through the documentation and I did not see anything around how to stop them. So I assumed that if I just remove it from the `schedule.yml` file it would not get enqueued again. I then tried deleting `schedule.yml` file completely, but that did not work either. 

I had to comment out the body of the job to stop it from processing. The job continues to run but just does nothing.

I am curious what the recommended way of stopping a job is. I am sure I am just missing something in the docs. I am curious though why what I tried did not work.

Thanks!

## Version Info

rails: `7.0.4`
sidekiq-cron: `1.9.1`
