### ISSUE TITLE
Add support for `retry` option

### ISSUE THREAD

**Issue by noahfpf** [sidekiq-cron/sidekiq-cron#496]
We're integrating sidekiq-cron as a replacement for cron jobs in part for the automatic retry support. However we don't want jobs to retry indefinitely. For example, in our case a job that runs every 15 minutes doesn't need to retry at all, and a job that runs nightly shouldn't retry after the end of the day.

We can use `sidekiq_options retry: 5` or the like in the Job class (see [doc](https://github.com/sidekiq/sidekiq/wiki/Error-Handling#configuration)), but the retry value is dependent on the scheduling, so we'd rather include it in `schedule.yml`, like:

```yml
parse_emails_job:
  cron: 'every 15 minutes'
  class: 'ParseEmails'
  retry: false # or 5, or retry_for: 15.minutes
```

The case for supporting this configuration option seems similar to the case for supporting `queue`.

Would you be open to a PR?
