### ISSUE TITLE
Review web UI translations

### ISSUE THREAD

**Issue by markets** [sidekiq-cron/sidekiq-cron#505]
We provide translations for the web part, but actually some files missed updates for years, so some languages are not fully complete. We should review all current files: [`lib/sidekiq/cron/locales`](https://github.com/sidekiq-cron/sidekiq-cron/tree/7609325b58d310dc8222745665f84e00557a9d92/lib/sidekiq/cron/locales). The reference is the English version. Maybe we can use Copilot/ChatGPT to fix this?

**Comment by satyakampandya** [comment]
I’d like to suggest organizing the translation keys into more specific categories for better structure and maintainability. For example, we could group action-related keys like this:

```yaml
en:
  actions:
    enqueue_now: Enqueue Now
    enable_all: Enable All
    disable_all: Disable All
    enqueue_all: Enqueue All
    delete_all: Delete All
    enable: Enable
    disable: Disable
```
We can follow the same practice of categorization for other keys as well.
