### ISSUE TITLE
Dynamic arguments

### ISSUE THREAD

**Issue by krystof-k** [sidekiq-cron/sidekiq-cron#536]
*Opening new issue based on #533.*

I would like to be able to pass dynamic arguments to a cron job, for example:

```yaml
Do something since:
  class: DoSomethingSinceJob
  args: [<%= 2.days.ago.to_s %>]
  cron: every day
```

Currently, this is not possible, because ERB is evaluated at the time of Sidekiq boot and all jobs would have the same argument value.
